"""empty message

Revision ID: 82c15adf8fab
Revises: 65f54d067407
Create Date: 2017-06-08 21:54:19.217538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c15adf8fab'
down_revision = '65f54d067407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
